export const tasks = [
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'work',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'groceries',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'assignment',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'work',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'groceries',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'assignment',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'work',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'groceries',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'assignment',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'work',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'groceries',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'assignment',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'work',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
    {
        title:'Clean all the dishes',
        description:'I will have to clean the dishes and arraged them properly before 4:00pm WAT',
        category:'groceries',
        expire: '03/10/2023',
        createdat:'02/09/2023',
    },
]